/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './resources/views/**/*.blade.php',
    './app/Livewire/**/*.php',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed':               '#c3f400',
        'primary-fixed-dim':           '#abd600',
        'primary':                     '#ffffff',
        'on-primary':                  '#283500',
        'on-primary-fixed':            '#161e00',
        'on-primary-fixed-variant':    '#3c4d00',
        'on-primary-container':        '#556d00',
        'primary-container':           '#c3f400',
        'inverse-primary':             '#506600',
        'surface-tint':                '#abd600',
        'secondary':                   '#c8c6c5',
        'secondary-container':         '#474746',
        'secondary-fixed':             '#e5e2e1',
        'secondary-fixed-dim':         '#c8c6c5',
        'on-secondary':                '#313030',
        'on-secondary-container':      '#b7b5b4',
        'on-secondary-fixed':          '#1c1b1b',
        'on-secondary-fixed-variant':  '#474746',
        'tertiary':                    '#ffffff',
        'tertiary-container':          '#ffdad8',
        'tertiary-fixed':              '#ffdad8',
        'tertiary-fixed-dim':          '#ffb3b0',
        'on-tertiary':                 '#68000f',
        'on-tertiary-container':       '#b6353a',
        'on-tertiary-fixed':           '#410006',
        'on-tertiary-fixed-variant':   '#8c1520',
        'surface':                     '#131313',
        'surface-dim':                 '#131313',
        'surface-bright':              '#3a3939',
        'surface-container-lowest':    '#0e0e0e',
        'surface-container-low':       '#1c1b1b',
        'surface-container':           '#201f1f',
        'surface-container-high':      '#2a2a2a',
        'surface-container-highest':   '#353534',
        'surface-variant':             '#353534',
        'background':                  '#131313',
        'on-background':               '#e5e2e1',
        'on-surface':                  '#e5e2e1',
        'on-surface-variant':          '#c4c9ac',
        'inverse-surface':             '#e5e2e1',
        'inverse-on-surface':          '#313030',
        'outline':                     '#8e9379',
        'outline-variant':             '#444933',
        'error':                       '#ffb4ab',
        'error-container':             '#93000a',
        'on-error':                    '#690005',
        'on-error-container':          '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter':          '16px',
        'stack-sm':        '12px',
        'touch-target-min':'48px',
        'stack-md':        '24px',
        'base':            '8px',
        'margin-mobile':   '20px',
        'stack-lg':        '40px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm':           ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg':         ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
  corePlugins: {
    preflight: false, // prevent fighting Bootstrap during migration
  },
  plugins: [
    require('@tailwindcss/forms')({ strategy: 'class' }),
  ],
}
